name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # Uses github secrets
    env:
      NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
      NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
      NODE_ENV: 'production'

    steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Read node version from `.nvmrc` file
      - id: nvmrc
        uses: browniebroke/read-nvmrc-action@v1

      - uses: actions/setup-node@v1
        with:
          # use the output from the action
          node-version: '${{ steps.nvmrc.outputs.node_version }}'

      - name: Install `node_modules`
        run: npm install

      - name: Build project
        run: npm run build

      - name: Export static files
        run: npm run export

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out